name: Build and Deploy Deaf-Date Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
          
      - name: Remove builded app from work dir
        run: |
          rm -rf /docker/app/deaf-date-server/dist

      - name: Pull Server Repository
        run: |
          cd /docker/app/deaf-date-server
          git pull origin main

      - name: Stop and Remove Existing Containers
        run: |
          docker compose -f /docker/compose/deaf-date-server/docker-compose.yml down

      - name: Build Server Docker Image
        run: |
          cd /docker/compose/deaf-date-server
          docker compose -f docker-compose.yml build --no-cache

      - name: Start Server Docker Container
        run: |
          cd /docker/compose/deaf-date-server
          docker compose -f docker-compose.yml up -d

      - name: Wait for Services to Start
        run: |
          sleep 10

      - name: Verify Server Container
        run: |
          if ! docker ps | grep -q deaf-date-server-deaf-date-server-1; then
            echo "Server container is not running." && exit 1
          fi

      - name: Deployment Completed
        run: echo "Build and deployment process completed successfully."
